# Site settings
name: Akshay Ayyanchira
title: Akshay Ayyanchira | iOS Mobile and Microsoft Hololens App Developer
description: iOS developer and an AR enthusiast
url: http://ayyanchira.github.io/
baseurl: ""
email: ayyanchira.akshay@gmail.com
cover: https://brittanychiang.com/img/og.png
logo: https://brittanychiang.com/img/emojis/technologist.png
resume: https://ayyanchira.github.io/resume.pdf
social:
  - title: email
    url: mailto:ayyanchira.akshay@gmail.com
  - title: twitter
    url: https://twitter.com/AAyyanchira
  - title: instagram
    url: https://www.instagram.com/akshayayyanchira
  - title: github
    url: https://github.com/Ayyanchira
  - title: linkedin
    url: https://www.linkedin.com/in/ayyanchira

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
